# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.2.0"
zap = "red-blox/zap@0.6.3"
mantle = "blake-mealey/mantle@0.11.14"
asphalt = "jacktabscode/asphalt@0.5.1"
