[tools]
wally = "upliftgames/wally@0.3.2"
stylua = "johnnymorganz/stylua@0.14.2"
rojo = "rojo-rbx/rojo@7.4.1"
selene = "kampfkarren/selene@0.26.1"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.1"
