title = "Paradoxical"
gitRepoUrl = "https://github.com/Phoenix9571/Paradoxical"

gitSourceBranch = "master"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "../.moonwave/static/paradox.jpg"

organizationName = "Phoenix9571"
projectName = "Paradoxical"
url = "https://Phoenix9571.github.io"
baseUrl = "/Paradoxical"
tagline = "Your project's tagline"

[navbar]

[[navbar.items]]
href = "https://discord.gg/585ztM9F"
label = "Discord"
position = "right"

[footer]
style = "dark"
copyright = "Copyright © 2024 Apollycn. Built with Moonwave and Docusaurus"

# [[footer.links]]
# title = "examples"

# [[footer.links.items]]
# label = "example"
# href = "https://example.com/"