# These are the locations of your .spec files (descendants are searched too)
roots = ["ReplicatedStorage/Paradoxical/tests"]

[extraOptions]
# Optionally, an extraOptions table can be passed to TestBootstrap
