[package]
name = "apollycn/paradoxical"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
matter = "matter-ecs/matter@0.7.1"
plasma = "matter-ecs/plasma@0.4.3"
react = "core-packages/react@17.0.1-rc.19"
react-roblox = "core-packages/react-roblox@17.0.1-rc.19"
react-spring = "chriscerie/react-spring@1.1.5"
t = "osyrisrblx/t@3.1.1"
squash = "data-oriented-house/squash@1.1.6"
yetanothernet = "yetanotherclown/yetanothernet@0.7.0"
spark = "nezuo/spark@0.2.1"

[server-dependencies]
lapis = "nezuo/lapis@0.2.11"

[dev-dependencies]
testez = "ruizukun-dev/testez@0.4.8"
rewire = "sayhisam1/rewire@0.3.0"