// Server generated by Zap v0.6.3 (https://github.com/red-blox/zap)
export const MyEvent: {
	on: (
		callback: (
			player: Player,
			value: {
				foo: number;
				bar: string;
			},
		) => void,
	) => () => void;
};
